name: 构建 iPXE 并嵌入自动执行脚本

on:
  workflow_dispatch:
    inputs:
      autoexec_path:
        description: '需要启动执行的脚本'
        required: false
        default: 'autoexec.ipxe'

jobs:
  bios:
    name: 构建 pcbios / ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: i386
          - arch: x86_64

    container:
      image: ghcr.io/netbootxyz/builder:latest
      options: --user root

    env:
      bindir: >-
        ${{ matrix.arch == 'i386' && 'bin' || 'bin-x86_64-pcbios' }}
      
    steps:
      - name: 创建工作目录
        working-directory: /
        run: |
          mkdir -p /workdir
          chown $USER:$GROUPS /workdir
          mkdir -p /workdir/bin
          chown $USER:$GROUPS /workdir/bin

      - name: 检出 autoexec.ipxe
        uses: actions/checkout@v4
        with:
          path: autoexec-config
          repository: zhoujinshi/AutoBuild-iPXE
          ref: master
          fetch-depth: 0

      - name: 检出 iPXE 源码
        uses: actions/checkout@v4
        with:
          path: ipxe-source
          repository: ipxe/ipxe
          ref: master
          fetch-depth: 0

      - name: 复制代码到工作目录
        run: |
          cp -r autoexec-config /workdir/
          cp -r ipxe-source /workdir/
          ls -la /workdir/

      - name: 准备 autoexec.ipxe
        working-directory: /workdir/autoexec-config
        run: |
          ls -la /workdir/ipxe-source
          echo "当前工作目录: $(pwd)"
          ls -la
          echo "尝试访问文件: ${{ inputs.autoexec_path }}"
          
          if [ -f "${{ inputs.autoexec_path }}" ]; then
            echo "找到文件，正在复制到 iPXE 源码目录..."
            cp "${{ inputs.autoexec_path }}" /workdir/ipxe-source/src/${{ inputs.autoexec_path }}
            echo "复制完成，验证目标文件:"
            ls -la /workdir/ipxe-source/src/${{ inputs.autoexec_path }}
          else
            echo "错误: 未找到 '${{ inputs.autoexec_path }}'"
            exit 1
          fi

          
          if [ -f "ca.crt" ]; then
            echo "找到文件，正在复制到 iPXE 源码目录..."
            cp "ca.crt" /workdir/ipxe-source/src/ca.crt
            echo "复制完成，验证目标文件:"
            ls -la /workdir/ipxe-source/src/ca.crt
          else
            echo "错误: 未找到 'ca.crt'"
            exit 1
          fi

      - name: 构建 iPXE
        working-directory: /workdir/ipxe-source/src
        run: |
          echo "当前工作目录: $(pwd)"
          make clean
          
          # 复制本地配置文件
          mkdir -p config/local
          cp -f /workdir/autoexec-config/local/* config/local/
          
          # 开始编译
          make ${{ env.bindir }}/ipxe.dsk \
               ${{ env.bindir }}/ipxe.iso \
               ${{ env.bindir }}/ipxe.lkrn \
               ${{ env.bindir }}/ipxe.pxe \
               ${{ env.bindir }}/undionly.kpxe \
               TRUST=ca.crt \
               EMBED=${{ inputs.autoexec_path }}
          cp ${{ env.bindir }}/ipxe.dsk /workdir/bin/${{ matrix.arch }}-ipxe.dsk
          cp ${{ env.bindir }}/ipxe.iso /workdir/bin/${{ matrix.arch }}-ipxe.iso
          cp ${{ env.bindir }}/ipxe.lkrn /workdir/bin/${{ matrix.arch }}-ipxe.lkrn
          cp ${{ env.bindir }}/ipxe.pxe /workdir/bin/${{ matrix.arch }}-ipxe.pxe
          cp ${{ env.bindir }}/undionly.kpxe /workdir/bin/${{ matrix.arch }}-undionly.kpxe
          cp ${{ inputs.autoexec_path }} /workdir/bin/${{ matrix.arch }}-${{ inputs.autoexec_path }}

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: ipxe-${{ matrix.arch }}-pcbios
          path: |
            /workdir/bin/*

  uefi:
    name: 构建 UEFI / ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - i386
          - x86_64
    container:
      image: ghcr.io/ipxe/ipxe-builder-${{ matrix.arch }}
      options: --user root
    env:
      bindir: bin-${{ matrix.arch }}-efi
    steps:
      - name: 创建工作目录
        working-directory: /
        run: |
          mkdir -p /workdir
          chown $USER:$GROUPS /workdir
          mkdir -p /workdir/bin
          chown $USER:$GROUPS /workdir/bin

      - name: 检出 autoexec.ipxe
        uses: actions/checkout@v4
        with:
          path: autoexec-config
          repository: zhoujinshi/AutoBuild-iPXE
          ref: master
          fetch-depth: 0

      - name: 检出 iPXE 源码
        uses: actions/checkout@v4
        with:
          path: ipxe-source
          repository: ipxe/ipxe
          ref: master
          fetch-depth: 0

      - name: 复制代码到工作目录
        run: |
          cp -r autoexec-config /workdir/
          cp -r ipxe-source /workdir/
          ls -la /workdir/

      - name: 准备 autoexec.ipxe
        working-directory: /workdir/autoexec-config
        run: |
          ls -la /workdir/ipxe-source
          echo "当前工作目录: $(pwd)"
          ls -la
          echo "尝试访问文件: ${{ inputs.autoexec_path }}"
          
          if [ -f "${{ inputs.autoexec_path }}" ]; then
            echo "找到文件，正在复制到 iPXE 源码目录..."
            cp "${{ inputs.autoexec_path }}" /workdir/ipxe-source/src/${{ inputs.autoexec_path }}
            echo "复制完成，验证目标文件:"
            ls -la /workdir/ipxe-source/src/${{ inputs.autoexec_path }}
          else
            echo "错误: 未找到 '${{ inputs.autoexec_path }}'"
            exit 1
          fi

          if [ -f "ca.crt" ]; then
            echo "找到文件，正在复制到 iPXE 源码目录..."
            cp "ca.crt" /workdir/ipxe-source/src/ca.crt
            echo "复制完成，验证目标文件:"
            ls -la /workdir/ipxe-source/src/ca.crt
          else
            echo "错误: 未找到 'ca.crt'"
            exit 1
          fi

      - name: 构建 iPXE
        working-directory: /workdir/ipxe-source/src
        run: |
          dnf install -y openssl || echo "openssl 安装失败"
          dnf install -y openssl-libs || echo "openssl-libs 安装失败"
          dnf install -y openssl-devel || echo "openssl-devel 安装失败"

          echo "当前工作目录: $(pwd)"
          make clean
          
          # 复制本地配置文件
          mkdir -p config/local
          cp -f /workdir/autoexec-config/local/* config/local/
          
          # 开始编译
          make ${{ env.bindir }}/ipxe.efi \
               ${{ env.bindir }}/ipxe.iso \
               ${{ env.bindir }}/snponly.efi \
               TRUST=ca.crt \
               EMBED=${{ inputs.autoexec_path }}
          cp ${{ env.bindir }}/ipxe.efi /workdir/bin/${{ matrix.arch }}-efi-ipxe.efi
          cp ${{ env.bindir }}/ipxe.iso /workdir/bin/${{ matrix.arch }}-efi-ipxe.iso
          cp ${{ env.bindir }}/snponly.efi /workdir/bin/${{ matrix.arch }}-efi-snponly.efi
          cp ${{ inputs.autoexec_path }} /workdir/bin/${{ matrix.arch }}-efi-${{ inputs.autoexec_path }}

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: ipxe-${{ matrix.arch }}-efi
          path: |
            /workdir/bin/*

  iso-usb:
    name: 生成 ISO 和 USB 格式文件
    runs-on: ubuntu-latest
    needs: [bios, uefi]
    container:
      image: ghcr.io/ipxe/ipxe-builder-${{ matrix.arch }}
      options: --user root
    env:
      fsbinaries: >-
        ipxe-i386-pcbios/i386-${DRIVERS}.lkrn
        ipxe-x86_64-pcbios/x86_64-${DRIVERS}.lkrn
        ipxe-i386-efi/i386-efi-${DRIVERS}.efi
        ipxe-x86_64-efi/x86_64-efi-${DRIVERS}.efi
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Download
        uses: actions/download-artifact@v7
        with:
          pattern: "{ipxe-i386-pcbios,ipxe-x86_64-pcbios,ipxe-i386-efi,ipxe-x86_64-efi}"

      - name: ISO + USB
        run: |
          # Provide an editable placeholder autoexec.ipxe for the USB image
          cat > autoexec.ipxe <<'EOF'
          #!ipxe
          echo
          prompt --key 0x02 --timeout 2000 \
              Press Ctrl-B for the iPXE command line... \
              && shell || autoboot
          EOF
          for DRIVERS in ipxe; do
              ./src/util/genfsimg -o ${DRIVERS}-multiarch.iso ${{ env.fsbinaries }}
              ./src/util/genfsimg -o ${DRIVERS}-multiarch.img -s autoexec.ipxe \
              ${{ env.fsbinaries }}
          done
          
      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: ipxe-combi-multiarch
          path: |
            ipxe-multiarch.iso
            ipxe-multiarch.img

  cleanup:
    name: 清理老的构建记录
    runs-on: ubuntu-latest
    needs: [iso-usb]
    steps:
      - name: 生成 release tag
        id: tag
        run: |
          echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
          touch release.txt
          cat >> release.txt <<EOF
          1、本固件为自动编译
          2、发行版中只提供完整的固件
          -- Build by Cnbbx @ with Github Action on $(date +"%Y.%m.%d-%H%M")
          🚀 Auto build | 自动编译
          EOF
          cat release.txt

      - name: 移除老的 workflow runs
        uses: zhoujinshi/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 3

      - name: 移除老的 Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
